;;; Update load path
(add-to-list 'load-path (expand-file-name "lisp" user-emacs-directory))

(require 'bootstrap)
(require 'init-base)
(require 'init-ui)
(require 'init-editor)
(require 'init-completion)
(require 'init-corfu)
(require 'init-treemacs)
(require 'init-meow)
(require 'init-better-emacs)
(require 'init-git)
(require 'init-multi-cursor)
(require 'init-copilot)
(require 'init-term)
(require 'init-whichkey)
(require 'init-ai)
(require 'init-utils)
(require 'my-macros)

;; programming language
(require 'init-prog)
(require 'init-common)
(require 'init-elixir)
;; (require 'init-typescript)
(require 'init-web)
(require 'init-go)
(require 'init-writing)

(provide 'init)
(put 'narrow-to-region 'disabled nil)
(put 'erase-buffer 'disabled nil)
